dataroot: /root/onethingai-tmp/Mesh/Manifold40-MAPS-96-3_1024/
mode: 'test'
augment_scale: True
augment_orient: False 
augment_deformation: False 
name: Maniflod40_finetune_meshmamba3D
checkpoint: 'fine_modelnet40.pkl'

model : {
  trans_dim: 384,
  depth: 12,
  drop_path_rate: 0.2,
  cls_dim: 40,
  num_heads: 6,
  group_size: 32,
  num_group: 128,
  encoder_dims: 384,
  bimamba_type: "v4",
  center_local_k: [4, 8, 16],
  ordering: False
}

train : {
  lr: 0.001, 
  weight_decay: 0.05,  
  optim: 'adamw',
  weight: 0.5,
  batch_size: 32,
  n_epoch: 100,
  max_epoch: 300,
  n_worker: 8,
  lr_milestones: '2',
  num_warmup_steps: 'none',
  seed: null,
}