dataroot: /root/onethingai-tmp/Mesh/ShapeNet-remesh_1024_t/
mode: 'train'
augment_scale: True
augment_orient: False 
augment_deformation: True 
name: meshmamba3D_0.6_shapenet_rand_cdl2
checkpoint: 'none'

model : {
  mask_ratio: 0.6,
  mask_type: 'rand',
  trans_dim: 384,
  depth: 12,
  drop_path_rate: 0.1,
  num_heads: 6,
  group_size: 32,
  num_group: 128,
  encoder_dims: 384,
  loss: 'cdl2',
  decoder_depth: 4,
  decoder_num_heads: 6,
  decoder_dims: 384,
  decoder_with_lfa: False,
  ordering: False,
  center_local_k: [4, 8, 16],
  bimamba_type: 'v4',
  weight: 0.5,
}
train : {
  lr: 0.001, 
  weight_decay: 0.05,  
  optim: 'adamw',
  weight: 0.5,
  batch_size: 32,
  n_epoch: 100,
  max_epoch: 300,
  n_worker: 8,
  lr_milestones: 'none',
  num_warmup_steps: '2',
  seed: null,
}